### ISSUE TITLE
3D Skybox in VR

### ISSUE THREAD

**Issue by mutp** [Unity-Technologies/UniversalRenderingExamples#26]
Hi, 

I'm facing issues getting the 3D Skybox to work in VR. After I add the TrackedPoseDriver script to the player cam, the planets get clipped during rotation.

**Comment by andybak** [comment]
Curious why you closed this. Did you solve it?

Other people might come across this issue if they hit a similar problem and there's nothing more frustrating than finding an issue closed without an explanation.

**Comment by mutp** [comment]
Sorry, yes. I did end up solving it. The biggest issue was the fact that I couldn't change the Renderer option on my Overlay camera in my project. I opened another issue for that - https://github.com/Unity-Technologies/UniversalRenderingExamples/issues/27

So, I just ended up using this project itself, and all I needed to do was add the "Tracked Pose Driver" script on all the cameras in my scene.
